apiVersion: v1
kind: ConfigMap
metadata:
  name: feedback-app-config
  namespace: default
data:
  DB_NAME: feedbackdb
  DB_HOST: feedback-api-db.cvhx0c6cxhvx.eu-central-1.rds.amazonaws.com
  DB_PORT: "5432"
