apiVersion: v1
kind: Service
metadata:
  name: feedback-app-api-service
  namespace: default
spec:
  selector:
    app: feedback-app-api
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-app-api
  template:
    metadata:
      namespace: default
      labels:
        app: feedback-app-api
        environment: test
    spec:
      containers:
      - name: feedback-app-backend-api
        image: galaataman/feedback-app:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: feedback-app-secret
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: feedback-app-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: feedback-app-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: feedback-app-secret
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: feedback-app-config
              key: DB_PORT
        livenessProbe:
          httpGet:
            path: /feedback 
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feedback-app-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feedback-app-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
