name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  GKE_CLUSTER: 'autopilot-cluster-2' # Update to your GKE cluster name
  GKE_ZONE: 'europe-west10-a' # Update to your cluster zone
  DEPLOYMENT_NAME: 'feedback-app' # Update to your deployment name
  DOCKER_REPO: 'atamankina' # Update to your Docker Hub repository
  DOCKER_IMAGE: 'feedback-app' # Update to your Docker image name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/363005759630/locations/global/workloadIdentityPools/github/providers/my-repo' # Update with your Workload Identity Provider resource name
  SERVICE_ACCOUNT_EMAIL: 'github-gke-deployer@flawless-psyche-440013-d0.iam.gserviceaccount.com' # Update with your Google service account email

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate to Google Cloud with Workload Identity Provider
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'

      # Authenticate Docker to Docker Hub
      - name: 'Docker Hub Login'
        uses: 'docker/login-action@v3'
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_ACCESS_TOKEN }}'

      # Get the GKE credentials so we can deploy to the cluster
      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      # Build and push Docker container to Docker Hub
      - name: 'Build and push Docker container'
        run: |-
          DOCKER_TAG="${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:${GITHUB_SHA}"

          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            .

          docker push "${DOCKER_TAG}"

      # Set up kustomize
      - name: 'Set up Kustomize'
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.3/kustomize_v5.4.3_linux_amd64.tar.gz
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster using configurations in the kubernetes_gke folder
      - name: 'Deploy to GKE'
        run: |-
          # Navigate to the kubernetes_gke directory
          cd kubernetes_gke
          
          # Update image tag in kustomize
          ../kustomize edit set image ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:latest=${DOCKER_TAG}

          # Build and apply the Kubernetes manifests
          ../kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
          kubectl get services -o wide
