name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  GKE_CLUSTER: 'autopilot-cluster-2'
  GKE_ZONE: 'europe-west10'
  DEPLOYMENT_NAME: 'feedback-app'
  DOCKER_REPO: 'galaataman'
  DOCKER_IMAGE: 'feedback-app'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/363005759630/locations/global/workloadIdentityPools/github/providers/my-repo'
  SERVICE_ACCOUNT_EMAIL: 'github-gke-deployer@flawless-psyche-440013-d0.iam.gserviceaccount.com'

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'

      - name: 'Docker Hub Login'
        uses: 'docker/login-action@v3'
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_ACCESS_TOKEN }}'

      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Build and push Docker container'
        run: |-
          DOCKER_TAG="${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:${GITHUB_SHA}"

          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            .

          docker push "${DOCKER_TAG}"

      - name: 'Deploy to GKE'
        run: |-
          cd kubernetes_gke

          echo "DOCKER_TAG is: ${DOCKER_TAG}"
          
          # Update the image in the deployment YAML file to use the latest tag
          sed -i "s|image: .*|image: ${DOCKER_TAG}|g" 3_api-deployment.yaml

          echo "Content of deployment.yaml after image update:"
          cat 3_api-deployment.yaml

          # Apply the updated Kubernetes manifests
          kubectl apply -f .
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
          kubectl get services -o wide
